apiVersion: v1
kind: Service
metadata:
  name: stress-app-svc
spec:
  selector:
    app: stress-app
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
